model_name: 'cnn'
model_params:
  timesteps: 600000
optimizer_params: #hard coded SGD optimizer
  lr: 0.003
  momentum: 0.9
  nesterov: True
  decay: 0.001
audio_files:
  use_raw_signal: True
  train_path: "/data/leonardo/OMGEmotionChallenge/Train_Set/audio"
  validation_path: "/data/leonardo/OMGEmotionChallenge/Validation_Set/audio"
ground_truth:
  train_path: "/data/leonardo/OMGEmotionChallenge/omg_TrainVideos.csv"
  validation_path: "/data/leonardo/OMGEmotionChallenge/omg_ValidationVideos.csv"
number_of_epochs: 200
batch_size: 64
nogpu: True # the code is so badly optimized that it does not use basically any GPU even if this is False