input_shape:
    - 256
    - 256
    - 3
batch_size: 16
ground_truth_path: "/Users/leonardoalchieri/Desktop/GIT/MMED/data.nosync/omg_ValidationVideos.csv"
frames_path: "/Users/leonardoalchieri/Desktop/GIT/MMED/data.nosync/Validation_Set/trimmed_faces/"
saving_path: "./extracted_features/Validation_Set/"